<?php

namespace AppBundle\Repository;

/**
 * ParseUrlListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParseUrlListRepository extends \Doctrine\ORM\EntityRepository
{
}
