guzzle:
    logging: true
    clients:
        guzzle.parse.start_point:
            base_url: "https://prozorro.gov.ua/tender/search/?status=active.auction"
            headers:
                Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"
                User-Agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
